version: "3.10"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_test_app
    ports:
      - "8081:8080"
    command: bash -c "uvicorn app:app --reload --host 0.0.0.0 --port 8080"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7.0.14
    container_name: dev_test_bd
    restart: always
    ports:
      - "6389:6379"